// ANALYTICS_FETCHED_SUCCESSFULLY
// ANALYTICS_FETCHED_UNSUCCESSFULLY

export const ANALYTICS = Object.freeze({
	ANALYTICS_FETCHED_SUCCESSFULLY: "ANALYTICS_FETCHED_SUCCESSFULLY",
	ANALYTICS_FETCHED_UNSUCCESSFULLY: "ANALYTICS_FETCHED_UNSUCCESSFULLY"
});