export const PLAYLIST = Object.freeze({
	GOT_PLAYLIST: "PLAYLIST.GOT_PLAYLIST",
	UPDATED_PLAYLIST: "PLAYLIST.UPDATED_PLAYLIST",
	CREATED_PLAYLIST: "PLAYLIST.CREATED_PLAYLIST",
	DELETED_PLAYLIST: "PLAYLIST.DELETED_PLAYLIST",
})