export const TRACK = Object.freeze({
	PLAYING_TRACK: "TRACK_NOW_PLAYING",
	PAUSED_TRACK: "TRACK_NOW_PAUSED",
	POS_CHANGE: "POS_CHANGE",
	HAS_DISCOVER_TRACKS: "HAS_DISCOVER_TRACKS",
	UPDATED_TRACK: "TRACK_HAS_UPDATED",
	GOT_ALL_TRACKS: "HAS_ALL_TRACKS",
	HAS_TRACK_COLLECTION: "HAS_TRACK_COLLECTION",
	HAS_MORE_DISCOVER_TRACKS: "HAS_MORE_DISCOVER_TRACKS"
})