export const USER = Object.freeze({
    PROFILE_UPDATE_SUCCESS: "PROFILE_UPDATE_SUCCEEDED",
    PROFILE_UPDATE_FAILURE: "PROFILE_UPDATE_FAILED",
    HAS_NEW_DATA: "USER_NEW_DATA",
    MUST_LOGOUT: "USER_LOGOUT",
    GOT_ALL_USERS: "ALL_USERS",
    VIEW_PROFILE: "VIEW_PROFILE",
    PROFILE_NOT_FOUND: "PROFILE_NOT_FOUND",
    LOADING: "USER_LOADING",
    SUCCESSFULLY_LOGGED_IN: "USER_LOGIN_SUCCEEDED",
    FAILED_LOGIN: "USER_LOGIN_FAILED",
    SUCCESSFULLY_REGISTERED: "USER_REGISTER_SUCCEEDED",
	FAILED_REGISTER: "USER_REGISTER_FAILED",
	TRACK_UPDATE_SUCCESS: "USER_UPDATED_TRACK",
    TRACK_DELETE_SUCCESS: "USER_DELETED_TRACK",
    GOT_TRACK: "USER_GOT_TRACK",
	TRACK_NOT_FOUND: "USER_TRACK_NOT_FOUND",
	MORE_TRACKS_FETCHED: "MORE_TRACKS_FETCHED"
})